theme: jekyll-theme-merlot
title: Chenxin's Individual Work (Tri 3)
description: "This github page is a source and version control for my replit with code from Tech Talk challenges and OO assignments. It also stores my notes and questions from Tech Talks, as well as my plan for preparing for the upcoming AP CSA exam."
markdown: kramdown
